-- Fall 2026 Volunteer Bulletin: Disability Program/Camp Volunteer
-- (Youth/Teenagers) Opportunities, grouped by Region -> County.
--
-- Run this once in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- Safe to run on the existing project: it adds the new region/county
-- columns (no-op if they already exist), clears the old sample volunteer
-- row(s), and inserts the full Fall 2026 list below.

alter table public.volunteers
  add column if not exists region text not null default '',
  add column if not exists county text not null default '';

delete from public.volunteers;

insert into public.volunteers
  (slug, organization_name, title, location, date, age_requirement, description, apply_url, region, county)
values
  ('scarc-volunteer', 'SCARC', 'Volunteer', 'Sussex County, NJ', 'Fall 2026', 'Not specified', 'Help with recreational activities, social events, and community programs for people with developmental disabilities. Volunteers help participants stay engaged, have fun, and build social connections.', 'https://www.scarc.org/volunteerism-at-scarc/', 'Northwest', 'Sussex'),
  ('special-olympics-new-team-young-athletes-event-volunteer', 'Special Olympics New Jersey', 'Team/Young Athletes/Event Volunteer', 'Sussex County, NJ', 'Fall 2026', 'Ages 14+', 'Help athletes during sports practices, activities, and competitions by assisting with drills, encouraging participation, and helping with events.', 'https://www.sonj.org/volunteer/', 'Northwest', 'Sussex'),
  ('scarc-event-volunteer', 'SCARC', 'Event Volunteer', 'Sussex County, NJ', 'Fall 2026', 'Not specified', 'Assist with SCARC activities and events through setup, activities, and participant support. Volunteers help create a welcoming environment where people with disabilities can participate and connect with others.', 'https://www.signupgenius.com/index.cfm?cs=09B6BADC8FBB8B107B0A640F5BB49BCB&eid=0EC3CFDEF5C8FB65&go=c.SignUpSearch&sortby=l.title', 'Northwest', 'Sussex'),
  ('aceing-autism-tennis-volunteer', 'ACEing Autism', 'Tennis Volunteer', 'Warren County, NJ', 'Fall 2026', 'Ages 13+', 'Help children with autism participate in tennis drills and games by providing encouragement and one-on-one assistance. This helps children develop confidence, physical skills, and social connections.', 'https://aceingautism.org/volunteer/', 'Northwest', 'Warren'),
  ('pillar-care-continuum-activity-volunteer', 'Pillar Care Continuum', 'Activity Volunteer', 'Warren County, NJ', 'Fall 2026', 'Not specified', 'Help individuals with disabilities participate in school activities, sports, recreation, and community events. Volunteers encourage participation while helping create friendships and a stronger sense of inclusion.', 'https://pillarnj.org/volunteer/', 'Northwest', 'Warren'),
  ('the-arc-of-somerset-county-camp-activity-volunteer', 'The Arc of Somerset County', 'Camp/Activity Volunteer', 'Warren County, NJ', 'Fall 2026', 'Not specified', 'Assist with games, crafts, outdoor activities, and other recreational programs for children with disabilities. Volunteers help campers have fun, socialize, and participate in activities alongside others.', 'https://www.thearcofsomerset.org/the-arc-foundation-of-somerset-county/index.html', 'Northwest', 'Warren'),
  ('the-arc-of-morris-county-recreation-event-volunteer', 'The Arc of Morris County', 'Recreation/Event Volunteer', 'Morris County, NJ', 'Fall 2026', 'Not specified', 'Help with recreational programs, community activities, and events for individuals with developmental disabilities. Volunteers encourage social interaction and make it easier for participants to enjoy and take part in their community.', 'https://arcmorris.org/get-involved/volunteer-opportunities', 'Northwest', 'Morris'),
  ('liquid-church-special-needs-volunteer', 'Liquid Church', 'Special Needs Volunteer', 'Morris County, NJ', 'Fall 2026', 'Not specified', 'Support children with special needs during activities and events, helping them participate alongside their peers. Volunteers help promote friendship, belonging, and an inclusive environment.', 'https://www.liquidchurch.com/special-needs', 'Northwest', 'Morris'),
  ('epoch-high-school-volunteer', 'EPOCH', 'High School Volunteer', 'Morris County, NJ', 'Fall 2026', 'Not specified', 'Help children with special needs with games, arts and crafts, cooking, library visits, and other activities. Volunteers encourage children to socialize, try new activities, and feel included.', 'https://epochmadison-nj.com/', 'Northwest', 'Morris'),
  ('mane-stream-sidewalker-horse-leader-volunteer', 'Mane Stream', 'Sidewalker / Horse Leader Volunteer', 'Hunterdon County, NJ', 'Fall 2026', 'Ages 14+', 'Act as sidewalkers and horse leaders during weekly adaptive riding and therapy sessions for children with physical, developmental, and cognitive challenges. Sidewalkers stay alongside young riders during lessons to provide physical support, encouragement, and help them follow the instructor''s prompts.', 'https://www.manestreamnj.org/volunteeropportunities', 'West-Central', 'Hunterdon'),
  ('borough-of-high-adaptive-sports-buddy-volunteer', 'Borough of High Bridge – Adaptive Athletics', 'Adaptive Sports Buddy Volunteer', 'Hunterdon County, NJ', 'Fall 2026', 'Ages 14–18', 'Act as 1-on-1 "buddies" on the field during adaptive sports programs, helping athletes learn skills, play safely, and build friendships in a team environment.', 'https://highbridge.org/adaptive-athletics/', 'West-Central', 'Hunterdon'),
  ('highbridge-youth-soccer-1-on-1-buddy-volunteer', 'Highbridge Youth Soccer', '1-on-1 Buddy Volunteer', 'Hunterdon County, NJ', 'Fall 2026', 'Teen volunteers', 'Serve as a 1-on-1 buddy paired with a player for the season to guide them through basic drills, keep them safe on the field, adapt games to their needs, and encourage them every step of the way.', 'https://app.teamlinkt.com/register/find/highbridgeyouthsoccer', 'West-Central', 'Hunterdon'),
  ('greater-somerset-county-ymca-saturdays-in-motion-volunteer', 'Greater Somerset County YMCA', 'Saturdays in Motion Volunteer', 'Somerset County, NJ', 'Fall 2026', 'Not specified', 'Get matched with a child for two hours on Saturdays to play together in the gym, help them navigate obstacle courses, and swim together in the pool.', 'https://www.gscymca.org/programs/adaptive-all-abilities/saturdays-in-motion/', 'West-Central', 'Somerset'),
  ('special-olympics-new-jersey-junior-unified-partner-buddy', 'Special Olympics New Jersey', 'Junior Unified Partner/Buddy', 'Somerset County, NJ', 'Fall 2026', 'Not specified', 'Serve as a Junior Unified Partner/Buddy, introducing young kids to foundational sports skills (jumping, balancing, throwing) through play-based games in a small group setting.', 'https://www.sonj.org/participation-requirements/', 'West-Central', 'Somerset'),
  ('matheny-medical-and-classroom-therapy-support-volunteer', 'Matheny Medical and Educational Center', 'Classroom & Therapy Support Volunteer', 'Somerset County, NJ', 'Fall 2026', 'High school students', 'Work directly alongside therapists and special-education staff to help young students engage in adapted classroom play, art therapy, storytime, and recreational games.', 'https://matheny.org/volunteering/', 'West-Central', 'Somerset'),
  ('adaptive-baseball-buddy-program-baseball-buddy-volunteer', 'Adaptive Baseball Buddy Program', 'Baseball Buddy Volunteer', 'Mercer County, NJ', 'Fall 2026', 'Not specified', 'Get assigned to one child for the fall baseball season to help them hit the ball, push/guide their wheelchair or run with them around the bases, and celebrate every play with them.', 'https://www.signupgenius.com/go/8050E45A9AF2EA4F94-60509427-2026#/', 'West-Central', 'Mercer'),
  ('hamilton-area-ymca-adaptive-sports-buddy', 'Hamilton Area YMCA', 'Adaptive Sports Buddy', 'Mercer County, NJ', 'Fall 2026', 'Not specified', 'Act as a 1-on-1 athletic buddy during fall adaptive sports clinics.', 'https://www.hamiltonymca.org/about-us/youth-volunteer-connection', 'West-Central', 'Mercer'),
  ('friendship-circle-friendship-circle-home-visit-volunteer', 'Friendship Circle', 'Friendship Circle Home Visit Volunteer', 'Mercer County, NJ', 'Fall 2026', 'Teen volunteers', 'Get paired 1-on-1 with a specific child for weekly 1-hour home visits during the school year — hang out, play LEGOs, work on crafts, or play video games to give that child a dedicated teenage friend.', 'https://www.friendshipcircle.com/online/volunteer/', 'West-Central', 'Mercer'),
  ('toms-river-fc-field-buddy-volunteer', 'Toms River FC', 'Field Buddy Volunteer', 'Ocean County, NJ', 'Fall 2026', 'Teen volunteers', 'Work 1-on-1 as a field buddy to guide young players through simple drills, help adapt the game to their abilities, and keep the environment supportive.', 'https://www.tomsriverfc.com/college-recruiting', 'Shore Region', 'Ocean'),
  ('jackson-soccer-club-sports-buddy-volunteer', 'Jackson Soccer Club', 'Sports Buddy Volunteer', 'Ocean County, NJ', 'Fall 2026', 'Not specified', 'Act as a 1-on-1 sports buddy for children with special needs, helping them practice kicking, passing, and running drills while cheering them on throughout the games.', 'https://www.jacksonsoccer.com/Default.aspx?tabid=755736', 'Shore Region', 'Ocean'),
  ('special-olympics-new-jersey-young-athletes-buddy-volunteer', 'Special Olympics New Jersey', 'Young Athletes Buddy Volunteer', 'Ocean County, NJ', 'Fall 2026', 'Teen volunteers', 'Serve as a Buddy during fall weekend clinics, working directly with young kids to help them navigate obstacle courses, practice basic motor skills (such as throwing and balancing), and play inclusive active games.', 'https://www.sonj.org/sports/young-athletes/', 'Shore Region', 'Ocean'),
  ('the-arc-of-atlantic-county-recreation-volunteer', 'The Arc of Atlantic County', 'Recreation Volunteer', 'Atlantic County, NJ', 'Fall 2026', 'Not specified', 'Participate in and aid recreational activities and other events.', 'https://thearcatlantic.org/volunteers/', 'Shore Region', 'Atlantic'),
  ('faces-4-autism-childcare-volunteer', 'Faces 4 Autism', 'Childcare Volunteer', 'Atlantic County, NJ', 'Fall 2026', 'Not specified', 'Assist with childcare activities and assist with snacks and more.', 'https://faces4autism.org/volunteer/', 'Shore Region', 'Atlantic'),
  ('atlantic-center-for-peer-support-volunteer', 'Atlantic Center for Independent Living', 'Peer Support Volunteer', 'Atlantic County, NJ', 'Fall 2026', 'Not specified', 'Support youth-focused empowerment, peer mentoring coordination, or social enrichment workshops.', 'https://www.atlanticcil.org/peer-support', 'Shore Region', 'Atlantic'),
  ('the-arc-of-cape-may-county-volunteer', 'The Arc of Cape May County', 'Volunteer', 'Cape May County, NJ', 'Fall 2026', 'Not specified', 'Support recreational activities, social events, and community programs for individuals with disabilities.', 'https://arcofcapemay.org/get-involved-menu/volunteer/', 'Southern Tip', 'Cape May'),
  ('faces-4-autism-childcare-volunteer-cape-may', 'Faces 4 Autism', 'Childcare Volunteer', 'Cape May County, NJ', 'Fall 2026', 'Not specified', 'Assist with childcare activities and assist with snacks and more.', 'https://faces4autism.org/volunteer/', 'Southern Tip', 'Cape May'),
  ('cape-may-county-community-volunteer', 'Cape May County Special Services School District', 'Community Volunteer', 'Cape May County, NJ', 'Fall 2026', 'Not specified', 'Enrich the educational program, increase supervision of students, contribute to school safety, and strengthen relationships between the school district and community.', 'https://cmcspecialservices.org/community/how-to-become-a-volunteer/', 'Southern Tip', 'Cape May'),
  ('the-arc-of-burlington-county-social-program-volunteer', 'The Arc of Burlington County', 'Social Program Volunteer', 'Burlington County, NJ', 'Fall 2026', 'Not specified', 'Assist with social nights, dances, seasonal celebrations, and day programs designed to help youth and adults with intellectual and developmental disabilities build friendships.', 'https://arcofburlington.org/how-to-help/volunteer/volunteer.html', 'South-West', 'Burlington'),
  ('moorestown-department-of-recreation-program-volunteer', 'Moorestown Department of Parks and Recreation', 'Recreation Program Volunteer', 'Burlington County, NJ', 'Fall 2026', 'Not specified', 'This summer and recreational program offers swimming, arts and crafts, music, sports, and special fun events for children and young adults with special needs.', 'https://www.moorestown.nj.us/504/Special-Needs-Programs', 'South-West', 'Burlington'),
  ('advancing-opportunities-community-program-volunteer', 'Advancing Opportunities', 'Community Program Volunteer', 'Burlington County, NJ', 'Fall 2026', 'Not specified', 'Community-based program providing fun theme nights, craft activities, and local outings for children registered with the New Jersey Children''s System of Care.', 'https://advopps.org/community-based-drop-off-programs/', 'South-West', 'Burlington'),
  ('raise-the-bar-family-services-buddy-support-volunteer', 'Raise the Bar Family Services', 'Buddy Support Volunteer', 'Camden County, NJ', 'Fall 2026', 'Not specified', 'Provide hands-on help, buddy support, and engagement during fun monthly youth activities and games for participants.', 'https://form.jotform.com/262034760033144?utm_id=97758_v0_s00_e0_tv2_a1demo08209ox8', 'South-West', 'Camden'),
  ('camden-county-division-county-social-program-volunteer', 'Camden County Division of Programming for Individuals with disABILITIES and Special Needs', 'County Social Program Volunteer', 'Camden County, NJ', 'Fall 2026', 'Not specified', 'Assist staff and participants during fun county-sponsored social activities, such as monthly dinner dances, bingo nights, adaptive sports, and arts and crafts.', 'https://www.camdencounty.com/service/disabilities-special-needs/', 'South-West', 'Camden'),
  ('special-events-4-special-kids-recreational-events-volunteer', 'Special Events 4 Special Kids', 'Recreational Events Volunteer', 'Camden County, NJ', 'Fall 2026', 'Not specified', 'Help run completely free, fun-filled recreational events, social gatherings, and seasonal celebrations.', 'https://se4sk.org/', 'South-West', 'Camden');
